# Generated by Django 4.2 on 2023-08-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_selling_price', models.FloatField()),
                ('product_discounted_price', models.FloatField()),
                ('product_details', models.TextField()),
                ('product_quantity', models.IntegerField()),
                ('product_category', models.CharField(choices=[('IP', 'I-Phone'), ('NK', 'Nokia'), ('XI', 'Xiaomi'), ('1P', '1Plus'), ('ZT', 'ZTE')], max_length=2)),
                ('product_image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
